### ISSUE TITLE
Конфигурационные файлы

### ISSUE THREAD

**Issue by mshornikov** [Klonochkin/react-ts-application#2]
https://docs.github.com/en/pages
https://www.redhat.com/en/topics/devops/what-is-ci-cd
https://docs.github.com/en/actions
https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#publishing-with-a-custom-github-actions-workflow
https://docs.github.com/en/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages

```yml
name: GitHub Pages
run-name: ${{ github.actor }} is rolling out a new version of the app 🚀

on:
  push:

jobs:
  Build-and-Deploy:
    permissions:
      contents: read
      pages: write
      id-token: write

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist repository
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
```
